### ISSUE TITLE
Task type 6 audio not playing

### ISSUE THREAD

**Issue by anjasam** [engagelab/morfologi#41]
* fix audio when words are clicked

**Comment by nesnass** [comment]
@anjasam  The sound already seems to be working - do you have an example Task I can check? May be that there are sounds missing in the CMS..

**Comment by anjasam** [comment]
@nesnass The sounds are not missing in the cms. Task number 33 was not working yesterday when the kids were trying (on the ipad) could it be something with objects that they can click and drag?
